RespuestasOchoBall={'Si',
'No',
'Puede ser',
'No cacho',
'Preguntame de nuevo, que no te cacho',
'Que eri weon, como preguntai esa wea',
'Hay una wea llamada google, demas sabe',
'Pensandolo bien, yo creo que',
'Anda a acostarte mejor',
'Puede que si',
'Puede que no',
'Nose pero tuki',
'Mira mira, mi duda es Cuanto cobra tu mamita?',
'Hablando con el consejo, llegamos a la conclusion que si',
'Hablando con el consejo, llegamos a la conclusion que no',
'Nose, espero haberte ayudado',
'Dudooooso',
'Ni idea, pero que nunca se te olvide que: "http://1.bp.blogspot.com/-9wjvTzU2ZdU/VUFjTHagKHI/AAAAAAAAAS0/htlDmkmZNj8/s1600/FormulaGeneral.png" '}

respuestasOchoBall=list(RespuestasOchoBall)